"""Add solution to exercise

Revision ID: 33f241ab9b2f
Revises: c0032c29c12b
Create Date: 2025-02-04 16:31:46.276732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '33f241ab9b2f'
down_revision: Union[str, None] = 'c0032c29c12b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercises', sa.Column('solution', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exercises', 'solution')
    # ### end Alembic commands ###
