"""Add student to models

Revision ID: fd00e76bd08a
Revises: 6ebb8b74b630
Create Date: 2025-01-31 16:25:26.338528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fd00e76bd08a'
down_revision: Union[str, None] = '6ebb8b74b630'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student_exercise',
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('In Progress', 'Submitted', 'Completed', name='exercise_status_2'), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('student_id', 'exercise_id')
    )
    op.create_table('student_hints',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('hint_id', sa.Integer(), nullable=False),
    sa.Column('given_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['hint_id'], ['exercise_hints.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('user_exercise')
    op.drop_table('user_hints')
    op.add_column('users', sa.Column('type', sa.String(length=50), nullable=False))
    op.drop_index('ix_users_user_id', table_name='users')
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=True)
    op.drop_column('users', 'user_id')
    op.drop_column('users', 'first_name')
    op.drop_column('users', 'last_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('first_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.create_index('ix_users_user_id', 'users', ['user_id'], unique=True)
    op.drop_column('users', 'type')
    op.create_table('user_hints',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('hint_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('given_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['hint_id'], ['exercise_hints.id'], name='user_hints_hint_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_hints_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='user_hints_pkey')
    )
    op.create_table('user_exercise',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('exercise_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('In Progress', 'Submitted', 'Completed', name='exercise_status'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], name='user_exercise_exercise_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_exercise_user_id_fkey'),
    sa.PrimaryKeyConstraint('user_id', 'exercise_id', name='user_exercise_pkey')
    )
    op.drop_table('student_hints')
    op.drop_table('student_exercise')
    op.drop_table('students')
    # ### end Alembic commands ###
